/* 图片资源 */
var imgSrcArr = [
    '../images/answer/donghua.gif',//
    '../images/answer/3.gif',//
    '../images/answer/answer_bg.jpg',//
    '../images/answer/answer_customer.jpg',//
    '../images/answer/alert.png',//
    '../images/answer/alreadyUsed.png',//
    '../images/answer/anew.png',//
    '../images/answer/answer_butOff.png',//
    '../images/answer/answer_butOn.png',//
    '../images/answer/answer_completeBg.png',//
    '../images/answer/answer_completeT1.png',//
    '../images/answer/answer_completeT2.png',//
    '../images/answer/answer_completeT3.png',//
    '../images/answer/answer_homeBg.png',//
    '../images/answer/answer_musicOff.png',//
    '../images/answer/answer_musicOn.png',//
    '../images/answer/answer_number.png',//
    '../images/answer/answer_paper.png',//
    '../images/answer/answer_perfectButOff.png',//
    '../images/answer/answer_perfectButOn.png',//
    '../images/answer/answer_prize.png',//
    '../images/answer/answer_ranking_list.png',//
    '../images/answer/answer_ruleBg.png',//
    '../images/answer/answer_start_btn.png',//
    '../images/answer/answer_topic.png',//
    '../images/answer/answerHaveBeen.png',//
    '../images/answer/answerNotUsedUp.png',//
    '../images/answer/arm_guard.png',//
    '../images/answer/body_parts.png',//
    '../images/answer/challenge_share.png',//
    '../images/answer/cheek_parts.png',//
    '../images/answer/daoNumber_1.png',//
    '../images/answer/daoNumber_2.png',//
    '../images/answer/daoNumber_3.png',//
    '../images/answer/dish.png',//
    '../images/answer/genderOff.png',//
    '../images/answer/genderOn.png',//
    '../images/answer/homeBg1.png',//
    '../images/answer/homeBg2.png',//
    '../images/answer/homeBg3.png',//
    '../images/answer/homeBg4.png',//
    '../images/answer/jiantou_left.png',//
    '../images/answer/know.png',//
    '../images/answer/leftDoor.png',//
    '../images/answer/leftHand.png',//
    '../images/answer/light.png',//
    '../images/answer/man_right_hand.png',//
    '../images/answer/mans.png',//
    '../images/answer/poster.png',//
    '../images/answer/postOff.png',//
    '../images/answer/postOn.png',//
    '../images/answer/result_1.jpg',//
    '../images/answer/result_2.jpg',//
    '../images/answer/result_3.jpg',//
    '../images/answer/result_4.jpg',//
    '../images/answer/result_5.jpg',//
    '../images/answer/result_6.jpg',//
    '../images/answer/result_7.jpg',//
    '../images/answer/result_8.jpg',//
    '../images/answer/result_9.jpg',//
    '../images/answer/result_10.jpg',//
    '../images/answer/stage_bgs.jpg',//
    '../images/answer/rankBack.png',//
    '../images/answer/result.png',//
    '../images/answer/result_hint.png',//
    '../images/answer/right_hands.png',//
    '../images/answer/rightDoor.png',//
    '../images/answer/rink_arrow.png',//
]